<a href="https://colab.research.google.com/github/vigneswar-123/DA2/blob/main/e_comer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
upload=files.upload()

Saving e_comerece.csv to e_comerece.csv

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("e_comerece.csv")
df.head()

,Tenure,WarehouseToHome,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,DaySinceLastOrder,CashbackAmount,Churn
0,15.0,29.0,4,Laptop & Accessory,3,Single,2,0,7.0,143.32,0
1,7.0,25.0,4,Mobile,1,Married,2,0,7.0,129.29,0
2,27.0,13.0,3,Laptop & Accessory,1,Married,5,0,7.0,168.54,0
3,20.0,25.0,4,Fashion,3,Divorced,7,0,NaN,230.27,0
4,30.0,15.0,4,Others,4,Single,8,0,8.0,322.17,0

In [40]:
df.head()

,Tenure,WarehouseToHome,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,DaySinceLastOrder,CashbackAmount,Churn
0,15.0,29.0,4,Laptop & Accessory,3,Single,2,0,7.0,143.32,0
1,7.0,25.0,4,Mobile,1,Married,2,0,7.0,129.29,0
2,27.0,13.0,3,Laptop & Accessory,1,Married,5,0,7.0,168.54,0
3,20.0,25.0,4,Fashion,3,Divorced,7,0,NaN,230.27,0
4,30.0,15.0,4,Others,4,Single,8,0,8.0,322.17,0

In [41]:
df['DaySinceLastOrder'] = df['DaySinceLastOrder'].fillna(0)

In [42]:
display(df.head())

,Tenure,WarehouseToHome,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,DaySinceLastOrder,CashbackAmount,Churn
0,15.0,29.0,4,Laptop & Accessory,3,Single,2,0,7.0,143.32,0
1,7.0,25.0,4,Mobile,1,Married,2,0,7.0,129.29,0
2,27.0,13.0,3,Laptop & Accessory,1,Married,5,0,7.0,168.54,0
3,20.0,25.0,4,Fashion,3,Divorced,7,0,0.0,230.27,0
4,30.0,15.0,4,Others,4,Single,8,0,8.0,322.17,0

In [44]:
df['Tenure']=df['Tenure'].fillna(df['Tenure'].mean())

In [43]:
df['WarehouseToHome']=df['WarehouseToHome'].fillna(df['WarehouseToHome'].mean())

In [53]:
mean_day=df['DaySinceLastOrder'].mean()
print(mean)
mean_ware=df['WarehouseToHome'].mean()
print(mean_ware)
mean_sat=df['SatisfactionScore'].mean()
print(mean_sat)
mean_ten=df['Tenure'].mean()
print(mean_ten)
mean_cash=df['CashbackAmount'].mean()
print(mean_cash)

4.286729256533874
15.650583244962885
3.0883024613042376
10.08139845209501
176.7074194366912

In [57]:
result = df[df['WarehouseToHouse'] > mean_ware]['Churn'].value_counts()
print(result)

Churn
0    1187
1     293
Name: count, dtype: int64

In [58]:
result = df[df['DaySinceLastOrder'] > mean_day]['Churn'].value_counts()
print(result)

Churn
0    1288
1     167
Name: count, dtype: int64

In [59]:
result = df[df['SatisfactionScore'] > mean_sat]['Churn'].value_counts()
print(result)

Churn
0    1235
1     319
Name: count, dtype: int64

In [60]:
result = df[df['Tenure'] > mean_ten]['Churn'].value_counts()
print(result)

Churn
0    1491
1      73
Name: count, dtype: int64

In [61]:
result = df[df['CashbackAmount'] > mean_cash]['Churn'].value_counts()
print(result)

Churn
0    1304
1     157
Name: count, dtype: int64

In [63]:
result2=df[(df['WarehouseToHome'] > mean_ware)&(df['DaySinceLastOrder'] > mean_day)&(df['SatisfactionScore'] > mean_sat)&(df['Tenure'] > mean_ten)&(df['CashbackAmount'] > mean_cash)]['Churn'].value_counts()
print(result2)

Churn
0    65
1     2
Name: count, dtype: int64