<a href="https://colab.research.google.com/github/vigneswar-123/DA2/blob/main/e_comer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import files
upload=files.upload()

Saving e_comerece.csv to e_comerece.csv

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("e_comerece.csv")
df.head()

,Tenure,WarehouseToHome,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,DaySinceLastOrder,CashbackAmount,Churn
0,15.0,29.0,4,Laptop & Accessory,3,Single,2,0,7.0,143.32,0
1,7.0,25.0,4,Mobile,1,Married,2,0,7.0,129.29,0
2,27.0,13.0,3,Laptop & Accessory,1,Married,5,0,7.0,168.54,0
3,20.0,25.0,4,Fashion,3,Divorced,7,0,NaN,230.27,0
4,30.0,15.0,4,Others,4,Single,8,0,8.0,322.17,0

In [6]:
df.head()

,Tenure,WarehouseToHome,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,DaySinceLastOrder,CashbackAmount,Churn
0,15.0,29.0,4,Laptop & Accessory,3,Single,2,0,7.0,143.32,0
1,7.0,25.0,4,Mobile,1,Married,2,0,7.0,129.29,0
2,27.0,13.0,3,Laptop & Accessory,1,Married,5,0,7.0,168.54,0
3,20.0,25.0,4,Fashion,3,Divorced,7,0,NaN,230.27,0
4,30.0,15.0,4,Others,4,Single,8,0,8.0,322.17,0

In [7]:
df['DaySinceLastOrder'] = df['DaySinceLastOrder'].fillna(0)

In [8]:
display(df.head())

,Tenure,WarehouseToHome,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,DaySinceLastOrder,CashbackAmount,Churn
0,15.0,29.0,4,Laptop & Accessory,3,Single,2,0,7.0,143.32,0
1,7.0,25.0,4,Mobile,1,Married,2,0,7.0,129.29,0
2,27.0,13.0,3,Laptop & Accessory,1,Married,5,0,7.0,168.54,0
3,20.0,25.0,4,Fashion,3,Divorced,7,0,0.0,230.27,0
4,30.0,15.0,4,Others,4,Single,8,0,8.0,322.17,0

In [9]:
df['Tenure']=df['Tenure'].fillna(df['Tenure'].mean())

In [10]:
df['WarehouseToHome']=df['WarehouseToHome'].fillna(df['WarehouseToHome'].mean())

In [13]:
mean_day=df['DaySinceLastOrder'].mean()
print(mean_day)
mean_ware=df['WarehouseToHome'].mean()
print(mean_ware)
mean_sat=df['SatisfactionScore'].mean()
print(mean_sat)
mean_ten=df['Tenure'].mean()
print(mean_ten)
mean_cash=df['CashbackAmount'].mean()
print(mean_cash)

4.286729256533874
15.650583244962885
3.0883024613042376
10.08139845209501
176.7074194366912

In [15]:
result1 = df[df['WarehouseToHome'] > mean_ware]['Churn'].value_counts()
print(result1)

Churn
0    1187
1     293
Name: count, dtype: int64

In [17]:
result2 = df[df['DaySinceLastOrder'] > mean_day]['Churn'].value_counts()
print(result2)

Churn
0    1288
1     167
Name: count, dtype: int64

In [18]:
result3 = df[df['SatisfactionScore'] > mean_sat]['Churn'].value_counts()
print(result3)

Churn
0    1235
1     319
Name: count, dtype: int64

In [19]:
result4 = df[df['Tenure'] > mean_ten]['Churn'].value_counts()
print(result4)

Churn
0    1491
1      73
Name: count, dtype: int64

In [20]:
result5= df[df['CashbackAmount'] > mean_cash]['Churn'].value_counts()
print(result5)

Churn
0    1304
1     157
Name: count, dtype: int64

In [21]:
result6=df[(df['WarehouseToHome'] > mean_ware)&(df['DaySinceLastOrder'] > mean_day)&(df['SatisfactionScore'] > mean_sat)&(df['Tenure'] > mean_ten)&(df['CashbackAmount'] > mean_cash)]['Churn'].value_counts()
print(result6)

Churn
0    65
1     2
Name: count, dtype: int64

In [22]:
result7=df[(df['WarehouseToHome'] > mean_ware)&(df['DaySinceLastOrder'] > mean_day)]['Churn'].value_counts()
print(result7)

Churn
0    491
1     76
Name: count, dtype: int64

In [24]:
result8=df[(df['Tenure'] > mean_ware)&(df['DaySinceLastOrder'] > mean_day)]['Churn'].value_counts()
print(result8)

Churn
0    408
1     14
Name: count, dtype: int64

In [25]:
'''
there are 4 main root couses
if we want to find on what conditions we 64 conditions
based on that that in what condition the churns are more we will identify that is the root couse
'''

'\nthere are 4 main root couses\nif we want to find on what conditions we 64 conditions \nbased on that that in what condition the churns are more we will identify that is the root couse\n'